version=0.10.2
buildNumber=102

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx12g -XX:MaxMetaspaceSize=2g

# Gradle Daemon JVM arguments
# Increase the memory allocated to the Gradle Daemon for better performance.
org.gradle.jvmargs=-Xmx12g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Enable Gradle build cache for faster builds
org.gradle.caching=true

# Enable Gradle configuration cache for faster builds
# Use 'warn' to see potential problems without failing the build.
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

org.gradle.parallel=true

# Kotlin Multiplatform Project Settings
kotlin.mpp.enableCInteropCommonization=true

# Android specific properties
android.nonTransitiveRClass=true
android.useAndroidX=true

# Xcode
kotlin.apple.xcodeCompatibility.nowarn=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false

#buildkonfig.flavor=dev
