# Uncomment the next line to define a global platform for your project
platform :ios, '18.5'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'ComposeApp', :path => '../composeApp'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'

end
