[versions]
agp = "9.4.0"

# Android
androidxCore = "1.19.0"
androidxAppcompat = "1.8.0"
androidxActivity = "1.13.0"
androidxTestExt = "1.3.0"
androidxTestEspresso = "3.7.0"
androidxLifecycleRuntime = "2.11.0"
androidxComposeBom = "2026.08.00"
androidxCredential = "1.6.0"

# Jetbrains
kotlin = "2.4.10"
kotlinGradlePlugin = "2.4.10"
kotlinxSerialization = "1.11.0"
kotlinxCoroutines = "1.11.0"
kotlinxDatetime = "0.8.0-0.6.x-compat"
lifecycle = "2.11.0"
composeHotReload = "1.2.0"
composeMultiplatform = "1.12.0"
kotlin-wrappers = "2026.9.1"

# Google
googleServices = "4.5.0"
googleGms = "22.0.0"
googleId = "1.2.0"
googleKsp = "2.3.11"
googleFirebaseBom = "34.18.0"

# Firebase
gitliveFirebase = "2.7.0"
mirzemehdiKmpAuth = "3.0.6"
googleFirebaseCommon = "21.0.0"
googleFirebaseAuth = "23.2.1"

# Java
junit = "4.13.2"

# 3rd Party
ktor = "3.5.2"
koin = "4.2.2"
kevinnzouComposeWebviewMultiplatform = "2.0.3"

# material
googleMaterial = "1.14.0"
composeMaterial3 = "1.9.0"
composeMaterial = "1.7.3"

# kermit
kermit = "2.1.0"

# KSafe
ksafe = "3.2.0"

# JVM
slf4j = "2.0.19"
logback = "1.6.3"

#kopykat = "0.13.0"
mapstruct = "1.6.3"

buildkonfig = "0.22.0"
#buildkonfigGradlePlugin = "latest_version"

# test version
kotlinxCoroutinesTest = "1.11.0"
#ktorClientMock = "2.3.2"
mockk = "1.14.11"

turbine = "1.2.1"
robolectric = "4.16.1"
kotlinStdlib = "2.4.10"
runner = "1.7.0"
core = "1.7.0"

[libraries]
# Android
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-credentials = { group = "androidx.credentials",name = "credentials", version.ref = "androidxCredential" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidxCredential" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntime" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# JetBrains
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlin-wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlin-wrappers" }
compose-ui-test-core = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "composeMultiplatform" }
compose-ui-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "composeMultiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeMaterial" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }

# Google
google-gms-play-service-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googleGms" }
google-googleid= { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleId" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "googleFirebaseBom" }
#google-firebase-config = { group = "comm.google.firebase", name = "firebase-config", version.ref = "firebase"}
# Optional, include if using firebase auth
google-firebase-auth = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "googleFirebaseAuth" }
google-firebase-common = { module = "com.google.firebase:firebase-common-ktx", version.ref = "googleFirebaseCommon" }
# Optional, include if using firebase analytics
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

# 3rd party
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin"}
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-resources = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
kevinnzou-compose-webview-multiplatform = { group = "io.github.kevinnzou", name = "compose-webview-multiplatform", version.ref = "kevinnzouComposeWebviewMultiplatform" }
gitlive-firebase-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "gitliveFirebase" }
gitlive-firebase-firestore = { group = "dev.gitlive", name = "firebase-firestore", version.ref = "gitliveFirebase" }
gitlive-firebase-common = { group = "dev.gitlive", name = "firebase-common", version.ref = "gitliveFirebase" }
gitlive-firebase-analytics = { group = "dev.gitlive", name = "firebase-analytics", version.ref = "gitliveFirebase" }
mirzemehdi-kmpauth-google = { group = "io.github.mirzemehdi", name = "kmpauth-google", version.ref = "mirzemehdiKmpAuth"}
mirzemehdi-kmpauth-firebase = { group = "io.github.mirzemehdi", name = "kmpauth-firebase", version.ref = "mirzemehdiKmpAuth"}
mirzemehdi-kmpauth-uihelper = { group = "io.github.mirzemehdi", name = "kmpauth-uihelper", version.ref = "mirzemehdiKmpAuth"}
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit"}
touchlab-kermit-test = { module = "co.touchlab:kermit-test", version.ref = "kermit"}
anifantakis-ksafe = { module = "eu.anifantakis:ksafe", version.ref = "ksafe" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mapstruct-core = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
buildkonfig-gradle-plugin = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfig" }

# tests
mockk  = { module = "io.mockk:mockk", version.ref = "mockk" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
turbine-test = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
# android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library",  version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Jetbrains
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-Jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

# google
devtool-ksp = { id = "com.google.devtools.ksp", version.ref = "googleKsp" }
gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

# 3rd
ktorPlugin = { id = "io.ktor.plugin", version.ref = "ktor" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
